version: "3.9"

services:
  medical-solution-rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmd-medical-solution
    ports:
      - "5675:5672"  # Changed left port to avoid conflict with old project
      - "15675:15672" # Changed left port to avoid conflict with old project
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - mongo-cluster

  medical-solution-express:
    build: .
    depends_on:
      - medical-solution-rabbitmq
    env_file:
      - .env
    ports:
      - "4001:4000" # Changed left port to avoid conflict with old project
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    external: true  # Ensure this network is already created externally, or change to "driver: bridge" for internal use
