# version: "3.9"

# services:
#   medical-solution-rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmd-medical-solution
#     ports:
#       - "5673:5672"  # Changed left port to avoid conflict with old project
#       - "15673:15672" # Changed left port to avoid conflict with old project
#     environment:
#       RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
#       RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


#   medical-solution-express:
#     build: .
#     depends_on:
#       - medical-solution-rabbitmq
#     env_file:
#       - .env
#     ports:
#       - "4001:4000" # Changed left port to avoid conflict with old project
#     volumes:
#       - .:/app
#     command: npm run dev

version: "3.9"

services:
  medical-solution-rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmd-medical-solution
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  medical-solution-express:
    build: .
    depends_on:
      - medical-solution-rabbitmq
    env_file:
      - .env
    ports:
      - "4001:4000"
    volumes:
      - .:/app
    command: npm run dev

  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    command: mongod --replSet rs01
    volumes:
      - /opt/mongo1/:/data/db

  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    command: mongod --replSet rs01
    volumes:
      - /opt/mongo2/:/data/db

  mongo3:
    container_name: mongo3
    hostname: mongo3
    image: mongo
    expose:
      - 27017
    ports:
      - 30003:27017
    restart: always
    command: mongod --replSet rs01
    volumes:
      - /opt/mongo3/:/data/db

  mongo_init:
    image: mongo
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./rs-init.sh:/opt/rs-init.sh
    entrypoint: [ "/usr/bin/bash", "/opt/rs-init.sh" ]
